language: node_js
node_js:
  - 10.15.1

script:
  - yarn run build
  - yarn test

deploy:
  provider: npm
  skip_cleanup: true
  email: $EMAIL_ADDRESS
  api_key: $NPM_TOKEN
  on:
    branch: master    

notifications:
  email:
    - $EMAIL_ADDRESS
